version: '3.5'
services:

  wordpress:
    image: wordpress:php8.2-apache
    container_name: app_wp
    restart: always
    ports:
      - "8080:8080"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: user_db
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
      - /home/vagrant/configs/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - /home/vagrant/configs/apache/ports.conf:/etc/apache2/ports.conf
    networks:
      frontend:
        ipv4_address: 172.16.1.6
      backend:
        ipv4_address: 172.20.1.5

  proxy_server:
    image: nginx:1.25.3
    container_name: proxy
    restart: always
    volumes:
      - /home/vagrant/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/vagrant/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      frontend:
        ipv4_address: 172.16.1.5

  db:
    container_name: db_container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.20.1.4

volumes:
  wordpress:
  db:

networks:
  frontend:
    name: frontend_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
  backend:
    name: backend_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
