version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db_host
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - wordpress

