---
- name: Deploy WordPress
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      command: apk add docker
      ignore_errors: yes

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull WordPress image
      command: docker pull wordpress

    - name: Pull MariaDB image
      command: docker pull mariadb

    - name: Create a network
      command: docker network create wp_network

    - name: Run MySQL container
      command: docker run -d --name mariadb_container --network wp_network -e MYSQL_ROOT_PASSWORD=admin mariadb

    - name: Run WordPress container
      command: docker run -d --name wordpress_container --network wp_network -e WORDPRESS_DB_HOST=mariadb_container -e WORDPRESS_DB_PASSWORD=admin -p 8080:80 wordpress

